import { useLanguage } from '@/contexts/LanguageContext';
import Navbar from '@/components/Header';
import Footer from '@/components/Footer';
// Image URLs
import HeroImage from "@/assets/images/herosection.png";
export default function PrivacyPolicy() {
    const { dir, language } = useLanguage();
    const isRTL = dir === 'rtl';

    const sections = [
        {
            number: '1.',
            title: language === 'en' ? 'Information We Collect' : 'المعلومات التي نجمعها',
            content: language === 'en'
                ? 'We collect information you provide directly (such as name, work email, and contact details), information generated by your use of the platform (such as log data and usage metrics), and information from cookies or similar technologies.'
                : 'نجمع المعلومات التي تقدمها مباشرة (مثل الاسم والبريد الإلكتروني الخاص بالعمل وتفاصيل الاتصال)، والمعلومات الناتجة عن استخدامك للمنصة (مثل بيانات السجل ومقاييس الاستخدام)، والمعلومات من ملفات تعريف الارتباط أو التقنيات المماثلة.',
        },
        {
            number: '2.',
            title: language === 'en' ? 'How We Use Information' : 'كيف نستخدم المعلومات',
            isList: true,
            items: language === 'en'
                ? [
                    'Provide, maintain, and improve our services.',
                    'Personalize your experience and deliver relevant insights.',
                    'Communicate with you about updates, support, and marketing (if opted in).',
                    'Protect against fraud, abuse, and security incidents.',
                ]
                : [
                    'تقديم خدماتنا وصيانتها وتحسينها.',
                    'تخصيص تجربتك وتقديم رؤى ذات صلة.',
                    'التواصل معك بشأن التحديثات والدعم والتسويق (إذا وافقت على ذلك).',
                    'الحماية من الاحتيال والإساءة والحوادث الأمنية.',
                ],
        },
        {
            number: '3.',
            title: language === 'en' ? 'Legal Bases (Where Applicable)' : 'الأسس القانونية (حيثما ينطبق)',
            content: language === 'en'
                ? 'We process personal data based on consent, contractual necessity, compliance with legal obligations, and legitimate interests such as securing our services.'
                : 'نعالج البيانات الشخصية بناءً على الموافقة، والضرورة التعاقدية، والامتثال للالتزامات القانونية، والمصالح المشروعة مثل تأمين خدماتنا.',
        },
        {
            number: '4.',
            title: language === 'en' ? 'Sharing & Disclosure' : 'المشاركة والإفصاح',
            content: language === 'en'
                ? 'We may share information with trusted service providers, professional advisors, and business partners who perform services on our behalf, subject to appropriate confidentiality obligations. We may also disclose information to comply with legal requirements or protect our rights.'
                : 'قد نشارك المعلومات مع مزودي الخدمات الموثوقين والمستشارين المحترفين وشركاء الأعمال الذين يؤدون خدمات نيابةً عنا، وفقاً لالتزامات السرية المناسبة. كما قد نكشف عن المعلومات للامتثال للمتطلبات القانونية أو حماية حقوقنا.',
        },
        {
            number: '5.',
            title: language === 'en' ? 'Data Retention' : 'الاحتفاظ بالبيانات',
            content: language === 'en'
                ? 'We retain personal data only as long as necessary for the purposes described in this policy, unless a longer retention period is required or permitted by law.'
                : 'نحتفظ بالبيانات الشخصية فقط طالما كان ذلك ضرورياً للأغراض الموضحة في هذه السياسة، ما لم يكن القانون يستوجب أو يسمح بفترة احتفاظ أطول.',
        },
        {
            number: '6.',
            title: language === 'en' ? 'Security' : 'الأمان',
            content: language === 'en'
                ? 'We implement reasonable administrative, technical, and organizational measures to protect your information. No method of transmission or storage is fully secure.'
                : 'نطبق تدابير إدارية وتقنية وتنظيمية معقولة لحماية معلوماتك. لا توجد طريقة نقل أو تخزين آمنة تماماً.',
        },
        {
            number: '7.',
            title: language === 'en' ? 'International Transfers' : 'النقل الدولي',
            content: language === 'en'
                ? 'Your information may be processed in countries other than your own. We take steps to ensure appropriate safeguards are in place where required.'
                : 'قد تتم معالجة معلوماتك في دول أخرى غير بلدك. نتخذ خطوات لضمان وجود ضمانات مناسبة حيثما كان ذلك مطلوباً.',
        },
        {
            number: '8.',
            title: language === 'en' ? 'Your Rights & Choices' : 'حقوقك وخياراتك',
            content: language === 'en'
                ? 'Depending on your location, you may have rights to access, correct, delete, or restrict the processing of your personal data, and to withdraw consent. You can also opt out of marketing communications at any time.'
                : 'بناءً على موقعك الجغرافي، قد يحق لك الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها أو تقييد معالجتها، وسحب موافقتك. يمكنك أيضاً إلغاء الاشتراك في الاتصالات التسويقية في أي وقت.',
        },
        {
            number: '9.',
            title: language === 'en' ? 'Cookies' : 'ملفات تعريف الارتباط',
            content: language === 'en'
                ? 'We use cookies and similar technologies to enhance functionality and analytics. You can manage cookie preferences through your browser settings.'
                : 'نستخدم ملفات تعريف الارتباط والتقنيات المماثلة لتحسين الوظائف والتحليلات. يمكنك إدارة تفضيلات ملفات تعريف الارتباط من خلال إعدادات متصفحك.',
        },
        {
            number: '10.',
            title: language === 'en' ? 'Changes to This Policy' : 'التغييرات على هذه السياسة',
            content: language === 'en'
                ? 'We may update this policy from time to time. The "Last updated" date indicates when changes were made.'
                : 'قد نقوم بتحديث هذه السياسة من وقت لآخر. يشير تاريخ "آخر تحديث" إلى وقت إجراء التغييرات.',
        },
    ];

    return (
        <div className="min-h-screen flex flex-col bg-white">
            <Navbar />

            <main className="flex-1 pt-20">
              {/* Hero */}
<div className="relative w-full pl-5 pr-8 py-24 overflow-hidden">

  {/* Background Image */}
  <div className="absolute inset-0">
    <img
      src={HeroImage}
      alt="Hero Background"
      className="w-full h-full object-cover"
    />
    {/* Dark overlay */}
    <div className="absolute inset-0 bg-blue-900/40" />
  </div>

  {/* Content */}
  <div className="relative z-10 text-center">
    <p className="text-[#32a7b5] text-sm font-semibold uppercase tracking-widest mb-3">
      {language === 'en' ? 'Legal' : 'قانوني'}
    </p>
    <h1 className={`text-4xl md:text-6xl font-bold text-white mb-5 ${isRTL ? 'font-arabic' : 'font-display'}`}>
      {language === 'en' ? 'Privacy Policy' : 'سياسة الخصوصية'}
    </h1>
    <p className={`text-white/80 text-lg text-center leading-relaxed mb-4  ${isRTL ? 'font-arabic' : 'font-body'}`}>
      {language === 'en'
        ? 'This Privacy Policy explains how Deeplenze Technologies collects, uses, discloses, and safeguards your information when you use our services.'
        : 'توضح سياسة الخصوصية هذه كيفية قيام شركة ديب لنز للتقنيات بجمع معلوماتك واستخدامها والإفصاح عنها وحمايتها عند استخدامك لخدماتنا.'}
    </p>
    <p className="text-white/50 text-base">
      {language === 'en' ? 'Last updated: February 7, 2026' : 'آخر تحديث: ٧ فبراير ٢٠٢٦'}
    </p>
  </div>

</div>

                {/* Content */}
                <div className="w-full pl-5 pr-8 py-14">
                    <div className="space-y-10 max-w-4xl">
                        {sections.map((section) => (
                            <div key={section.number} className={isRTL ? 'text-right' : ''}>
                                <h2 className={`text-3xl font-bold text-slate-900 mb-3 ${isRTL ? 'font-arabic' : 'font-display'}`}>
                                    {section.number} {section.title}
                                </h2>

                                {section.isList && section.items ? (
                                    <ul className={`space-y-2 ${isRTL ? 'pr-6' : 'pl-6'}`}>
                                        {section.items.map((item, i) => (
                                            <li
                                                key={i}
                                                className={`text-slate-600 text-lg leading-relaxed list-disc ${isRTL ? 'font-arabic' : 'font-body'}`}
                                            >
                                                {item}
                                            </li>
                                        ))}
                                    </ul>
                                ) : (
                                    <p className={`text-slate-600 text-lg leading-relaxed ${isRTL ? 'font-arabic' : 'font-body'}`}>
                                        {section.content}
                                    </p>
                                )}
                            </div>
                        ))}
                    </div>

                    {/* Contact Us box */}
                    <div className="mt-14 border border-slate-200 rounded-xl p-8 bg-slate-50 max-w-4xl">
                        <h3 className={`text-2xl font-bold text-slate-900 mb-2 ${isRTL ? 'font-arabic' : 'font-display'}`}>
                            {language === 'en' ? 'Contact Us' : 'تواصل معنا'}
                        </h3>
                        <p className={`text-slate-600 text-lg ${isRTL ? 'font-arabic' : 'font-body'}`}>
                            {language === 'en'
                                ? <>If you have any questions about this policy, contact us at{' '}
                                    <a href="mailto:support@deeplenze.com" className="text-[#32a7b5] hover:underline">support@deeplenze.com</a>.</>
                                : <>إذا كانت لديك أي أسئلة حول هذه السياسة، تواصل معنا على{' '}
                                    <a href="mailto:support@deeplenze.com" className="text-[#32a7b5] hover:underline">support@deeplenze.com</a>.</>
                            }
                        </p>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}